on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: deployment
      run: echo "deploy"

    - name: failure
      run: |
        echo "Game pass!"

  ending_success:
      if: ${{ success() }}
      needs: deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Notify status failed on slack
          run: |
            echo "success job"

  ending_failed:
    if: ${{ failure() }}
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notify status failed on slack
        run: |
          echo "failure job"
