on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        ci_node_total: [2]
        ci_node_index: [0, 1]

    steps:
    - name: First node
      if: ${{ matrix.ci_node_index }} != '0'
      run: echo "Primer nodo"

    - name: Creating files
      env:
        CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
        CI_NODE_INDEX: ${{ matrix.ci_node_index }}
      run: |
        mkdir -p ./tmp
        echo "$CI_NODE_INDEX node SIN CHANGE" > "./tmp/test.$CI_NODE_INDEX.txt"
        ls -la ./tmp
    - uses: actions/upload-artifact@master
      with:
        name: test-${{ matrix.ci_node_index }}.txt
        path: ./tmp/test.${{ matrix.ci_node_index }}.txt
        retention-days: 2
    
  test-coverage-upload:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p tmp

      - uses: actions/download-artifact@master
        with:
          name: test-0.txt
          path: tmp/test-0

      - uses: actions/download-artifact@master
        with:
          name: test-1.txt
          path: tmp/test-1

      - run: ls -la tmp
      - run: ls -la ./tmp/test-0
      - run: ls -la ./tmp/test-1

